{% set name = "opentelemetry-instrumentation-mysql" %}
{% set version = "0.54b1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_mysql-{{ version }}.tar.gz
  sha256: de3a9367886523f30bd04b51edcf8d0777de7eac4a2467f52478231f51405b49

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - opentelemetry-api ~=1.12
    - opentelemetry-instrumentation-dbapi ==0.54b1
    - opentelemetry-instrumentation ==0.54b1
    # - opentelemetry-test-utils ==0.37b0
    # - opentelemetry-instrumentation-mysql 
    # - mysql-connector-python ~=8.0
    # - opentelemetry-test-utils ==0.38b0
    # - opentelemetry-instrumentation-mysql 
    # - mysql-connector-python ~=8.0
    # - opentelemetry-test-utils ==0.39b0
    # - opentelemetry-instrumentation-mysql 
    # - mysql-connector-python ~=8.0
    # - opentelemetry-test-utils ==0.40b0
    # - opentelemetry-instrumentation-mysql 
    # - mysql-connector-python ~=8.0
    # - opentelemetry-test-utils ==0.41b0
    # - opentelemetry-instrumentation-mysql 
    # - mysql-connector-python ~=8.0
    # - opentelemetry-test-utils ==0.42b0
    # - opentelemetry-instrumentation-mysql 
    # - mysql-connector-python ~=8.0
    # - opentelemetry-test-utils ==0.43b0
    # - opentelemetry-instrumentation-mysql 
    # - mysql-connector-python ~=8.0
    # - opentelemetry-test-utils ==0.44b0
    # - opentelemetry-instrumentation-mysql 
    # - mysql-connector-python ~=8.0
    # - mysql-connector-python ~=8.0
    # - mysql-connector-python ~=8.0
    # - mysql-connector-python ~=8.0
    # - mysql-connector-python <10.0,>=8.0
    # - mysql-connector-python <10.0,>=8.0
    # - mysql-connector-python <10.0,>=8.0
    # - mysql-connector-python <10.0,>=8.0
    # - mysql-connector-python <10.0,>=8.0
    # - mysql-connector-python <10.0,>=8.0
    # - mysql-connector-python <10.0,>=8.0
    # - mysql-connector-python <10.0,>=8.0
    # - mysql-connector-python <10.0,>=8.0
    # - mysql-connector-python <10.0,>=8.0
    # - mysql-connector-python <10.0,>=8.0
    # - mysql-connector-python <10.0,>=8.0
test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-mysql
  summary: OpenTelemetry MySQL instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - mariusvniekerk
